FROM node:20-alpine

WORKDIR /app

# Required for zlib-sync
RUN apk add --no-cache build-base python3

COPY package*.json ./
RUN npm install --save-dev

ENTRYPOINT ["/usr/bin/env"]

CMD [ "npm", "run", "dev" ]
